version: '3.1'
services:
  demo-mysql:
    container_name: navigation-mysql8
    image: mysql/mysql-server:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--lower_case_table_names=1", "--max_connections=2048", "--wait_timeout=3600" ]
    ports:
      - "13306:3306"
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d

  demo-adminer: # mysql web admin
    container_name: navigation-adminer
    image: adminer:4
    ports:
      - "18080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=demo-mysql8
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=tables-filter tinymce
  rabbitmq_container:
    image: rabbitmq:3.12-management
    container_name: rabbitmq_container
    ports:
      - "35672:5672"
      - "45672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=pixeller
      - RABBITMQ_DEFAULT_PASS=pixeller

